apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  selector:
    matchLabels:
      app: p-ser-search
  replicas: 1
  template:
    metadata:
      labels:
        app: p-ser-search
    spec:
      volumes:
        - name: app-config
          configMap:
            name: app-config
      containers:
        - name: search-container
          image: amanecopse/p-ser-search:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/share"
              name: app-config