name: search CI

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Add config yaml
        run: |
          mkdir -p ./src/main/resources; touch ./src/main/resources/application.yaml
          echo "${{secrets.TEST_CONFIG}}" > ./src/main/resources/application.yaml
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test