name: search CD

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Add config yaml
        run: |
          mkdir -p ./src/main/resources; touch ./src/main/resources/application.yaml
          echo "${{secrets.TEST_CONFIG}}" > ./src/main/resources/application.yaml
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USER }}/p-ser-search .
          docker push ${{ secrets.DOCKER_USER }}/p-ser-search
      - name: Execute remote ssh (pull origin)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd C:\workspace\p-ser-search && git pull origin develop
      - name: Execute remote ssh (switch branch)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd C:\workspace\p-ser-search && git switch develop
      - name: Execute remote ssh (redeploy)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd C:\workspace\p-ser-search && kubectl rollout restart deployment -n search-ns search-deployment
